spring.application.name=cloudpos

spring.datasource.url=jdbc:postgresql://localhost:5433/cloudpos
spring.datasource.username=cloudpos_user
spring.datasource.password=cloudpos_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

server.port=8080
